### ISSUE TITLE
no longer works with mruby2

### ISSUE THREAD

**Issue by dsisnero** [sdottaka/mruby-win32ole#1]
trying excel2.rb 

c:\Dominic\programming\repos\git\mruby\build\host\bin>mruby.exe excel2.rb
trace (most recent call last):
        [0] excel2.rb:12
excel2.rb:12: wrong number of arguments (ArgumentError)

c:\Dominic\programming\repos\git\mruby\build\host\bin>mruby --version
mruby 2.0.0 (2018-12-11)

**Comment by sdottaka** [comment]
Fixed in 9cb447d. Thank you for the report!

**Comment by dsisnero** [comment]
Thanks! it works now
